# Single Run Required

In [193]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import plotly.express as px
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense

In [194]:
dataset = "TitanData/TitanFullData.csv"
titan = pd.read_csv(dataset)

In [195]:
titan.shape

(370545, 6)

In [196]:
titan.dropna(inplace=True)

In [197]:
titan.to_csv("TitanData/TitanFullDataCleaned.csv")

In [198]:
titan.shape

(370404, 6)

In [199]:
rows = titan.shape[0]
train_limit = int(rows*0.8) + 1 # 80-20 split for test and train data

In [200]:
titan_train = titan[:train_limit]

In [201]:
titan_train

timestamp    open    high     low   close   volume
0       2017-01-02 09:15:00+05:30  327.00  327.05  326.00  326.60   1135.0
1       2017-01-02 09:16:00+05:30  326.70  327.00  326.70  327.00    489.0
2       2017-01-02 09:17:00+05:30  327.00  327.05  326.85  326.85   4360.0
3       2017-01-02 09:18:00+05:30  326.85  326.85  325.80  326.00   3979.0
4       2017-01-02 09:19:00+05:30  326.00  326.75  326.00  326.75    177.0
...                           ...     ...     ...     ...     ...      ...
296399  2020-03-18 11:59:00+05:30  939.20  942.50  939.00  940.35  11825.0
296400  2020-03-18 12:00:00+05:30  940.80  944.20  940.70  943.20  12666.0
296401  2020-03-18 12:01:00+05:30  943.25  943.35  939.00  940.05   9038.0
296402  2020-03-18 12:02:00+05:30  939.70  942.15  939.05  941.20   5171.0
296403  2020-03-18 12:03:00+05:30  941.20  941.90  938.30  939.45   6000.0

[296324 rows x 6 columns]

In [202]:
titan_train.to_csv("TitanData/TitanTrain.csv", index=False)

In [203]:
titan_test = titan[train_limit:]

In [204]:
titan_test

timestamp     open     high      low    close   volume
296404  2020-03-18 12:04:00+05:30   939.20   940.35   938.50   938.75   6475.0
296405  2020-03-18 12:05:00+05:30   938.65   939.25   938.00   938.50   5195.0
296406  2020-03-18 12:06:00+05:30   938.10   938.80   938.00   938.70   5400.0
296407  2020-03-18 12:07:00+05:30   938.00   939.75   938.00   939.75   7041.0
296408  2020-03-18 12:08:00+05:30   939.70   941.40   938.95   940.80  19337.0
...                           ...      ...      ...      ...      ...      ...
370540  2021-01-01 15:25:00+05:30  1559.95  1561.95  1559.05  1560.90   4822.0
370541  2021-01-01 15:26:00+05:30  1560.95  1561.00  1559.25  1559.30   4585.0
370542  2021-01-01 15:27:00+05:30  1559.85  1560.00  1557.65  1557.95   2869.0
370543  2021-01-01 15:28:00+05:30  1557.95  1560.00  1557.25  1559.65   4476.0
370544  2021-01-01 15:29:00+05:30  1559.65  1559.75  1558.00  1558.00   2246.0

[74080 rows x 6 columns]

In [205]:
titan_test.to_csv("TitanData/TitanTest.csv", index=False)

In [206]:
titan_train = titan_train.iloc[:, 1:2].values

In [207]:
titan_train

array([[327.  ],
       [326.7 ],
       [327.  ],
       ...,
       [943.25],
       [939.7 ],
       [941.2 ]])

# Load Dataset

In [2]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
from datetime import datetime
import plotly.express as px
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense

In [32]:
titan = pd.read_csv("TitanData/TitanFullDataCleaned.csv")

In [54]:
rows = titan.shape[0]
train_limit = int(rows*0.8) + 1 # 80-20 split for test and train data

In [3]:
titan_train = pd.read_csv("TitanData/TitanTrain.csv")

In [4]:
titan_train

timestamp    open    high     low   close   volume
0       2017-01-02 09:15:00+05:30  327.00  327.05  326.00  326.60   1135.0
1       2017-01-02 09:16:00+05:30  326.70  327.00  326.70  327.00    489.0
2       2017-01-02 09:17:00+05:30  327.00  327.05  326.85  326.85   4360.0
3       2017-01-02 09:18:00+05:30  326.85  326.85  325.80  326.00   3979.0
4       2017-01-02 09:19:00+05:30  326.00  326.75  326.00  326.75    177.0
...                           ...     ...     ...     ...     ...      ...
296319  2020-03-18 11:59:00+05:30  939.20  942.50  939.00  940.35  11825.0
296320  2020-03-18 12:00:00+05:30  940.80  944.20  940.70  943.20  12666.0
296321  2020-03-18 12:01:00+05:30  943.25  943.35  939.00  940.05   9038.0
296322  2020-03-18 12:02:00+05:30  939.70  942.15  939.05  941.20   5171.0
296323  2020-03-18 12:03:00+05:30  941.20  941.90  938.30  939.45   6000.0

[296324 rows x 6 columns]

In [5]:
titan_test = pd.read_csv("TitanData/TitanTest.csv")

In [6]:
titan_test

timestamp     open     high      low    close   volume
0      2020-03-18 12:04:00+05:30   939.20   940.35   938.50   938.75   6475.0
1      2020-03-18 12:05:00+05:30   938.65   939.25   938.00   938.50   5195.0
2      2020-03-18 12:06:00+05:30   938.10   938.80   938.00   938.70   5400.0
3      2020-03-18 12:07:00+05:30   938.00   939.75   938.00   939.75   7041.0
4      2020-03-18 12:08:00+05:30   939.70   941.40   938.95   940.80  19337.0
...                          ...      ...      ...      ...      ...      ...
74075  2021-01-01 15:25:00+05:30  1559.95  1561.95  1559.05  1560.90   4822.0
74076  2021-01-01 15:26:00+05:30  1560.95  1561.00  1559.25  1559.30   4585.0
74077  2021-01-01 15:27:00+05:30  1559.85  1560.00  1557.65  1557.95   2869.0
74078  2021-01-01 15:28:00+05:30  1557.95  1560.00  1557.25  1559.65   4476.0
74079  2021-01-01 15:29:00+05:30  1559.65  1559.75  1558.00  1558.00   2246.0

[74080 rows x 6 columns]

In [7]:
#titan_test = titan_train.test[:, 1:2].values

In [8]:
titan_train = titan_train.iloc[:, 1:2].values

In [9]:
titan_test = titan_test.iloc[:, 1:2].values

In [10]:
sc = MinMaxScaler(feature_range = (0, 1))
titan_train_scaled = sc.fit_transform(titan_train)

In [11]:
# titan_train_scaled

In [12]:
n_inputs = 200 # No of previous input values 
n_outputs = 20 # No of next values to predict

X_train = [] 
y_train = []

for i in range(n_inputs, len(titan_train_scaled)-n_outputs):
    X_train.append(titan_train_scaled[i-n_inputs: i, 0]) # Take last n_inputs values
    y_train.append(titan_train_scaled[i:i+n_outputs, 0]) # In y-train append next n_outputs values
    
X_train, y_train = np.array(X_train), np.array(y_train)

# for loop Starting from 10th value in the dataset until the last value in the dataset.
# We append 10 values to X-train and the next value to y-train.

In [13]:
X_train.shape

(296104, 200)

In [14]:
y_train.shape

(296104, 20)

In [15]:
y_train

array([[0.00136246, 0.00136246, 0.00136246, ..., 0.00173831, 0.00173831,
        0.00173831],
       [0.00136246, 0.00136246, 0.00136246, ..., 0.00173831, 0.00173831,
        0.00164435],
       [0.00136246, 0.00136246, 0.00131548, ..., 0.00173831, 0.00164435,
        0.00164435],
       ...,
       [0.57369039, 0.57322058, 0.57228095, ..., 0.57556965, 0.57660324,
        0.57810665],
       [0.57322058, 0.57228095, 0.57077754, ..., 0.57660324, 0.57810665,
        0.58040874],
       [0.57228095, 0.57077754, 0.57101245, ..., 0.57810665, 0.58040874,
        0.57707306]])

In [16]:
# print(titan_train_scaled)

In [17]:
X_train = np.reshape(X_train, newshape = (X_train.shape[0], X_train.shape[1], 1))

In [18]:
X_train.shape

(296104, 200, 1)

In [19]:
y_train = np.reshape(y_train, newshape = (y_train.shape[0], y_train.shape[1], 1))

In [20]:
y_train.shape

(296104, 20, 1)

In [21]:
regressor = Sequential()

In [22]:
n_units = 100
n_epochs = 10
batch_size = 512

regressor.add(LSTM(units = n_units, return_sequences = True, input_shape = (X_train.shape[1], 1)))

regressor.add(Dropout(rate = 0.2))

In [23]:
##add 2nd lstm layer
regressor.add(LSTM(units = n_units, return_sequences = True))
regressor.add(Dropout(rate = 0.2))##add 3rd lstm layer
regressor.add(LSTM(units = n_units, return_sequences = True))
regressor.add(Dropout(rate = 0.2))##add 4th lstm layer
regressor.add(LSTM(units = n_units, return_sequences = False))
regressor.add(Dropout(rate = 0.2))

In [24]:
regressor.add(Dense(units = n_outputs))
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [25]:
regressor.fit(x = X_train, y = y_train, batch_size = batch_size, epochs = n_epochs)

Epoch 1/10
579/579 [==============================] - 232s 371ms/step - loss: 0.0082
Epoch 2/10
579/579 [==============================] - 236s 408ms/step - loss: 0.0017
Epoch 3/10
579/579 [==============================] - 237s 410ms/step - loss: 0.0011
Epoch 4/10
579/579 [==============================] - 198s 342ms/step - loss: 8.0028e-04
Epoch 5/10
579/579 [==============================] - 254s 439ms/step - loss: 6.2382e-04
Epoch 6/10
579/579 [==============================] - 135s 232ms/step - loss: 4.9071e-04
Epoch 7/10
579/579 [==============================] - 136s 235ms/step - loss: 4.0214e-04
Epoch 8/10
579/579 [==============================] - 137s 237ms/step - loss: 3.3610e-04
Epoch 9/10
579/579 [==============================] - 137s 236ms/step - loss: 3.0192e-04
Epoch 10/10
579/579 [==============================] - 137s 236ms/step - loss: 2.7483e-04


In [26]:
real_stock_price = titan_test

In [33]:
titan_open = titan['open']

In [34]:
titan_open

0          327.00
1          326.70
2          327.00
3          326.85
4          326.00
           ...   
370399    1559.95
370400    1560.95
370401    1559.85
370402    1557.95
370403    1559.65
Name: open, Length: 370404, dtype: float64

In [35]:
inputs = titan_open[len(titan_open) - len(titan_test)-n_inputs:].values

In [36]:
inputs = inputs.reshape(-1, 1)

In [37]:
inputs = sc.transform(inputs)

In [38]:
inputs

array([[0.64806202],
       [0.64416256],
       [0.64204839],
       ...,
       [1.15978389],
       [1.15799859],
       [1.15959596]])

In [39]:
X_test = []
y_test = []

for i in range(n_inputs, len(inputs)-n_outputs): 
    X_test.append(inputs[i-n_inputs: i, 0])
    y_test.append(inputs[i:i+n_outputs, 0])
X_test = np.array(X_test)
y_test = np.array(y_test)
#make numpy array as 3D , adding num of indicator
X_test = np.reshape(X_test, newshape = (X_test.shape[0],  X_test.shape[1], 1))
y_test = np.reshape(y_test, newshape = (y_test.shape[0],  y_test.shape[1], 1))

In [40]:
X_test

array([[[0.64806202],
        [0.64416256],
        [0.64204839],
        ...,
        [0.58040874],
        [0.57707306],
        [0.5784825 ]],

       [[0.64416256],
        [0.64204839],
        [0.63819591],
        ...,
        [0.57707306],
        [0.5784825 ],
        [0.57660324]],

       [[0.64204839],
        [0.63819591],
        [0.6351891 ],
        ...,
        [0.5784825 ],
        [0.57660324],
        [0.57608645]],

       ...,

       [[1.16631431],
        [1.1668311 ],
        [1.16603242],
        ...,
        [1.15917313],
        [1.15809255],
        [1.15804557]],

       [[1.1668311 ],
        [1.16603242],
        [1.16603242],
        ...,
        [1.15809255],
        [1.15804557],
        [1.15912615]],

       [[1.16603242],
        [1.16603242],
        [1.16570355],
        ...,
        [1.15804557],
        [1.15912615],
        [1.15954898]]])

In [41]:
y_test

array([[[0.57660324],
        [0.57608645],
        [0.57556965],
        ...,
        [0.58224101],
        [0.5817712 ],
        [0.5792342 ]],

       [[0.57608645],
        [0.57556965],
        [0.57547569],
        ...,
        [0.5817712 ],
        [0.5792342 ],
        [0.57735494]],

       [[0.57556965],
        [0.57547569],
        [0.57707306],
        ...,
        [0.5792342 ],
        [0.57735494],
        [0.5789993 ]],

       ...,

       [[1.15912615],
        [1.15954898],
        [1.15968992],
        ...,
        [1.15875029],
        [1.15987785],
        [1.16081748]],

       [[1.15954898],
        [1.15968992],
        [1.15964294],
        ...,
        [1.15987785],
        [1.16081748],
        [1.15978389]],

       [[1.15968992],
        [1.15964294],
        [1.15992483],
        ...,
        [1.16081748],
        [1.15978389],
        [1.15799859]]])

In [42]:
X_test.shape

(74060, 200, 1)

In [43]:
y_test.shape

(74060, 20, 1)

In [44]:
predicted_stock_price = regressor.predict(X_test)

2315/2315 [==============================] - 56s 23ms/step


In [45]:
pred_backup = predicted_stock_price
predicted_stock_price

array([[0.5835758 , 0.5836734 , 0.58320624, ..., 0.58326066, 0.58312744,
        0.5832985 ],
       [0.58386207, 0.5839669 , 0.5834923 , ..., 0.58355135, 0.58340824,
        0.58358765],
       [0.5841161 , 0.5842259 , 0.58374715, ..., 0.5838096 , 0.58365834,
        0.58384436],
       ...,
       [1.1574104 , 1.1590542 , 1.1566398 , ..., 1.1575048 , 1.1576439 ,
        1.1564424 ],
       [1.1571987 , 1.1588392 , 1.15643   , ..., 1.1572932 , 1.1574347 ,
        1.1562313 ],
       [1.1569753 , 1.1586123 , 1.1562082 , ..., 1.1570694 , 1.1572132 ,
        1.156008  ]], dtype=float32)

In [46]:
predicted_stock_price.shape

(74060, 20)

In [47]:
predicted_stock_price = sc.inverse_transform(predicted_stock_price)

In [48]:
len(predicted_stock_price)

74060

In [49]:
predicted_stock_price

array([[ 946.62054,  946.7244 ,  946.22723, ...,  946.28516,  946.1434 ,
         946.32544],
       [ 946.9252 ,  947.0368 ,  946.5317 , ...,  946.5945 ,  946.4422 ,
         946.6331 ],
       [ 947.19556,  947.3124 ,  946.8029 , ...,  946.8694 ,  946.7084 ,
         946.9064 ],
       ...,
       [1557.324  , 1559.0734 , 1556.5039 , ..., 1557.4244 , 1557.5725 ,
        1556.2938 ],
       [1557.0986 , 1558.8446 , 1556.2806 , ..., 1557.1993 , 1557.3499 ,
        1556.0691 ],
       [1556.861  , 1558.603  , 1556.0446 , ..., 1556.9612 , 1557.1141 ,
        1555.8315 ]], dtype=float32)

In [50]:
predicted_stock_price.shape

(74060, 20)

In [55]:
timestamps = titan['timestamp'][train_limit:len(titan['timestamp'])-n_outputs]

In [56]:
len(timestamps)

74060

In [57]:
len(y_test)

74060

In [58]:
len(predicted_stock_price)

74060

In [59]:
timestamps.shape

(74060,)

In [60]:
real_stock_price.shape

(74080, 1)

In [61]:
# real_stock_price = real_stock_price[:, 0]
# real_stock_price.shape

In [62]:
#predicted_stock_price = real_stock_price+10
#predicted_stock_price = predicted_stock_price[:, 0]

In [63]:
predicted_stock_price.shape

(74060, 20)

In [64]:
predicted_stock_price

array([[ 946.62054,  946.7244 ,  946.22723, ...,  946.28516,  946.1434 ,
         946.32544],
       [ 946.9252 ,  947.0368 ,  946.5317 , ...,  946.5945 ,  946.4422 ,
         946.6331 ],
       [ 947.19556,  947.3124 ,  946.8029 , ...,  946.8694 ,  946.7084 ,
         946.9064 ],
       ...,
       [1557.324  , 1559.0734 , 1556.5039 , ..., 1557.4244 , 1557.5725 ,
        1556.2938 ],
       [1557.0986 , 1558.8446 , 1556.2806 , ..., 1557.1993 , 1557.3499 ,
        1556.0691 ],
       [1556.861  , 1558.603  , 1556.0446 , ..., 1556.9612 , 1557.1141 ,
        1555.8315 ]], dtype=float32)

In [65]:
# titan_predict_compare = {'Timestamps': list(timestamps), 'Real': list(real_stock_price), 'Predicted': list(predicted_stock_price)}

# titan_predict_df = pd.DataFrame(titan_predict_compare)

# titan_predict_df

In [66]:
y_test = np.reshape(y_test, newshape = (y_test.shape[0],  y_test.shape[1]))

In [67]:
y_test = sc.inverse_transform(y_test)

In [68]:
y_test - predicted_stock_price

array([[-7.42054443, -8.07442627, -8.12723389, ..., -1.08515625,
        -1.44337158, -4.32543945],
       [-8.2751709 , -8.9368042 , -8.53167725, ..., -1.89448242,
        -4.44219971, -6.63311768],
       [-9.09555664, -9.31237793, -7.10291748, ..., -4.86938477,
        -6.70837402, -5.15637207],
       ...,
       [ 1.82602539,  0.52663574,  3.24609375, ...,  1.32556152,
         2.37749023,  4.65617676],
       [ 2.50136719,  0.90539551,  3.41936035, ...,  2.75065918,
         3.60014648,  3.7809082 ],
       [ 2.88903809,  1.09697266,  3.95544434, ...,  3.98881836,
         2.73586426,  2.11845703]])

In [69]:
import numpy as np
def accuracy(real, pred):
    diff = real-pred
    diff_abs = np.absolute(real-pred)
    #print(diff_abs)
    ratio = diff_abs/real
    #print(ratio.shape)
    #print(ratio)
    rms = np.sqrt(np.mean(diff**2, axis=0))
    #print(rms)
    absolute = np.mean(diff_abs, axis=0)
    print("Absolute Avg Error = ", absolute)
    print("RMS Error = ", rms)

In [70]:
# import numpy as np
# def accuracy(real, pred):
#     diff = real-pred
#     diff_abs = np.absolute(real-pred)
#     rms = np.sqrt(np.mean(diff**2))
#     absolute = np.mean(diff_abs)
#     print("Absolute Avg Error = ", absolute)
#     print("RMS Error = ", rms)

In [71]:
accuracy(y_test, predicted_stock_price)

Absolute Avg Error =  [6.94515192 7.29190767 6.6690841  7.04039798 6.73191409 6.9723663
 7.24672891 7.31638902 6.85442125 7.23897343 7.20011136 7.28418432
 6.97592678 7.28107854 7.29803414 7.27986358 7.2561496  7.45277889
 7.42797868 7.47788346]
RMS Error =  [7.9194255  8.28002698 7.8071961  8.19146647 7.99039292 8.28066554
 8.60858743 8.73431431 8.37658188 8.78753574 8.81188126 8.94586891
 8.7346783  9.05559378 9.13094666 9.15685917 9.21023631 9.41781163
 9.44647052 9.5505641 ]


In [160]:
#titan_predict_df.columns[1:]

In [ ]:
#fig = px.line(titan, x=timestamps, y=real_stock_rice, title="Titan Prediction")
#fig = go.Figure(go.Scatter(titan_predict_df, x='Timestamps', y=titan_predict_df.columns[1:]))
# fig = go.Figure(go.Scatter(x=timestamps, y=predicted_stock_price))
fig = px.line(x = timestamps, y=[y_test[:, 0], predicted_stock_price[:, 0]])
fig.show()

In [ ]:
#fig = px.line(titan, x=timestamps, y=real_stock_rice, title="Titan Prediction")
#fig = go.Figure(go.Scatter(titan_predict_df, x='Timestamps', y=titan_predict_df.columns[1:]))
# fig = go.Figure(go.Scatter(x=timestamps, y=predicted_stock_price))
fig = px.line(x = timestamps, y=[y_test[:, 1], predicted_stock_price[:, 1]])
fig.show()

In [ ]:
#fig = px.line(titan, x=timestamps, y=real_stock_rice, title="Titan Prediction")
#fig = go.Figure(go.Scatter(titan_predict_df, x='Timestamps', y=titan_predict_df.columns[1:]))
# fig = go.Figure(go.Scatter(x=timestamps, y=predicted_stock_price))
fig = px.line(x = timestamps, y=[y_test[:, 2], predicted_stock_price[:, 2]])
fig.show()

In [ ]:
#fig = px.line(titan, x=timestamps, y=real_stock_rice, title="Titan Prediction")
#fig = go.Figure(go.Scatter(titan_predict_df, x='Timestamps', y=titan_predict_df.columns[1:]))
# fig = go.Figure(go.Scatter(x=timestamps, y=predicted_stock_price))
fig = px.line(x = timestamps, y=[y_test[:, 3], predicted_stock_price[:, 3]])
fig.show()

In [ ]:
#fig = px.line(titan, x=timestamps, y=real_stock_rice, title="Titan Prediction")
#fig = go.Figure(go.Scatter(titan_predict_df, x='Timestamps', y=titan_predict_df.columns[1:]))
# fig = go.Figure(go.Scatter(x=timestamps, y=predicted_stock_price))
fig = px.line(x = timestamps, y=[y_test[:, 4], predicted_stock_price[:, 4]])
fig.show()

In [166]:
regressor.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 200, 100)          40800     
                                                                 
 dropout (Dropout)           (None, 200, 100)          0         
                                                                 
 lstm_1 (LSTM)               (None, 200, 100)          80400     
                                                                 
 dropout_1 (Dropout)         (None, 200, 100)          0         
                                                                 
 lstm_2 (LSTM)               (None, 200, 100)          80400     
                                                                 
 dropout_2 (Dropout)         (None, 200, 100)          0         
                                                                 
 lstm_3 (LSTM)               (None, 100)               8

In [167]:
regressor.save('Models/{}inputs_{}units_{}epochs_{}batch_{}outputs'.format(n_inputs, n_units, n_epochs, batch_size, n_outputs))

INFO:tensorflow:Assets written to: Models/200inputs_100units_10epochs_512batch_20outputs\assets


INFO:tensorflow:Assets written to: Models/200inputs_100units_10epochs_512batch_20outputs\assets


Links:

https://towardsdatascience.com/basics-of-ohlc-charts-with-pythons-matplotlib-56d0e745a5be \
https://towardsdatascience.com/lstm-for-google-stock-price-prediction-e35f5cc84165 \
https://github.com/arpitgits/Stock-Market-predictions-using-different-ML-algorithms-for-swing-and-day-trading \
https://plotly.com/python/time-series/ \
https://plotly.com/python/getting-started/ \
https://www.investopedia.com/terms/o/ohlcchart.asp \
https://rapidapi.com/blog/best-stock-api/ \
https://www.moneycontrol.com/markets/indian-indices/ \
https://towardsdatascience.com/stock-market-analysis-in-python-part-1-getting-data-by-web-scraping-cb0589aca178 \
https://www.tensorflow.org/install/pip#windows-native_1 \
https://stackoverflow.com/questions/58142058/how-to-plot-multiple-lines-on-the-same-y-axis-using-plotly-express-in-python \
https://datascience.stackexchange.com/questions/82820/keras-predicts-nan-values \
https://www.tensorflow.org/tutorials/keras/save_and_load \
https://machinelearningmastery.com/difference-between-a-batch-and-an-epoch/ \
https://www.tensorflow.org/tensorboard/graphs \
https://neptune.ai/blog/installing-tensorflow-2-gpu-guide \
https://www.geeksforgeeks.org/using-jupyter-notebook-in-virtual-environment/ \
https://stackoverflow.com/questions/73424216/how-to-install-cudnn-and-cuda-toolkit-in-a-python-virtual-environment \
https://stackoverflow.com/questions/58068818/how-to-use-jupyter-notebooks-in-a-conda-environment \
https://www.tensorflow.org/tensorboard/graphs \
https://www.tensorflow.org/api_docs/python/tf/test/is_gpu_available \
https://stackoverflow.com/questions/44829085/tensorflow-not-running-on-gpu \
https://www.tensorflow.org/install/pip \
https://towardsdatascience.com/tensorflow-gpu-installation-made-easy-use-conda-instead-of-pip-52e5249374bc \
https://www.activestate.com/resources/quick-reads/how-to-install-keras-and-tensorflow/ \
https://keras.io/api/models/model_training_apis/ \
https://www.nseindia.com/all-reports \
https://www1.nseindia.com/products/content/debt/rdm/historical_rdm.htm \
https://www1.nseindia.com/products/content/equities/equities/eq_security.htm \
https://www.niftyindices.com/reports/historical-data \
https://groww.in/blog/most-volatile-stocks \
https://www.screener.in/screens/313326/high-volatility-stocks-a/ \
https://www.indmoney.com/articles/stocks/open-high-open-low-strategy-steps-to-execute-the-strategy \